#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    #test_upgrade_from.46990410c80669094c6feb34a843e02295f3eb73.name = "Last packagingv1 version"
    test_upgrade_from.7b24cbbd6a7c3c654326b3f582e82f7e19daca9f.name = "Upgrade from 2025.02.02~ynh1"
